import "./globals.css";
import Example from "@/components/navbar";
import { UserProvider } from './UserContext';
import { CartProvider } from "./CartContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider >
      <CartProvider>
        <html lang="en">
          <body>
            <Example/>
            <br></br>
            {children}
            <br></br>
          </body>
        </html>
      </CartProvider>
    </UserProvider >
  );
}
